#!/bin/bash

echo "🔥 Firebase Setup for ArtXchange"
echo "=================================="
echo ""
echo "✅ Frontend config: Updated with your Firebase project details"
echo "✅ Backend config: Updated with project ID 'fypdatabase-c8728'"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. 🌐 Go to Firebase Console: https://console.firebase.google.com/"
echo "2. 📁 Select your project: fypdatabase-c8728"
echo "3. ⚙️  Go to Project Settings → Service accounts tab"
echo "4. 🔑 Click 'Generate new private key'"
echo "5. 📥 Download the JSON file"
echo "6. 📂 Move it to your project:"
echo ""
echo "   mv ~/Downloads/fypdatabase-c8728-firebase-adminsdk-*.json \\"
echo "      \"$(pwd)/src/main/resources/firebase-service-account.json\""
echo ""
echo "7. 🗄️  Enable Firestore Database:"
echo "   - Go to Firestore Database in Firebase Console"
echo "   - Click 'Create database'"
echo "   - Choose 'Start in test mode'"
echo "   - Select location: asia-southeast1 (Singapore - closest to Malaysia)"
echo ""
echo "8. 🚀 Run the application:"
echo "   ./run-dev.sh"
echo ""
echo "🔍 Check if service account file exists:"
if [ -f "./src/main/resources/firebase-service-account.json" ]; then
    echo "   ✅ Service account file found!"
else
    echo "   ❌ Service account file NOT found - please download it from Firebase Console"
fi
echo ""
